# Generated by Django 4.2.7 on 2023-12-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='insight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='end_year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='impact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='pestle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
