# Generated by Django 4.2.7 on 2023-12-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companydata_insight_alter_companydata_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='start_year',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
