# Generated by Django 4.2.7 on 2023-12-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_companydata_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='added',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='published',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
