# Generated by Django 4.2.7 on 2023-12-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_companydata_added_alter_companydata_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
