# Generated by Django 4.2.7 on 2023-12-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_companydata_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='intensity',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='likelihood',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='relevance',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='title',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
